name: Deploy to Lambda
on: [push]
jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Zip up Dependencies
      if: github.ref == 'refs/heads/master'
      run:
        ls && pwd
        bash build_deps.sh
    - name: AWS Lambda Deploy
      if: github.ref == 'refs/heads/master'
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: asset-manager-altair-dashboard
        source: deployment-package.zip
        handler: lambda_entrypoint.lambda_handler
