name: QA

on: push

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Package
        run: |
          pip install -e . && pip install mypy
      - name: Run mypy
        run: |
          mypy asset_manager
  test-all:
    name: Test All
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Package
        run: |
          pip install -e . && pip install pytest
      - name: Run pytest
        run: |
          pytest
